export const queryKeys = {
  auth: {
    session: ['auth', 'session'],
    user: ['auth', 'user'],
  },
  company: {
    root: (companyId) => ['company', companyId],
    detail: (companyId) => ['company', companyId, 'detail'],
    clients: (companyId) => ['company', companyId, 'clients'],
    services: (companyId) => ['company', companyId, 'services'],
    invoices: (companyId) => ['company', companyId, 'invoices'],
    invoice: (invoiceId) => ['invoices', invoiceId],
    facturas: (companyId) => ['company', companyId, 'facturas'],
    factura: (facturaId) => ['facturas', facturaId],
    quotations: (companyId) => ['company', companyId, 'quotations'],
    quotation: (quotationId) => ['quotations', quotationId],
    reminders: (companyId) => ['company', companyId, 'reminders'],
    analytics: (companyId) => ['company', companyId, 'analytics'],
    dashboard: (companyId) => ['company', companyId, 'dashboard'],
    cobros: (companyId) => ['company', companyId, 'cobros'],
    users: (companyId) => ['company', companyId, 'users'],
    inventory: {
      root: (companyId) => ['company', companyId, 'inventory'],
      products: (companyId) => ['company', companyId, 'inventory', 'products'],
      categories: (companyId) => ['company', companyId, 'inventory', 'categories'],
      movements: (companyId) => ['company', companyId, 'inventory', 'movements'],
      operations: (companyId) => ['company', companyId, 'inventory', 'operations'],
      suppliers: (companyId) => ['company', companyId, 'inventory', 'suppliers'],
      warehouses: (companyId) => ['company', companyId, 'inventory', 'warehouses'],
      pendingDocs: (companyId) => ['company', companyId, 'inventory', 'pending-docs'],
      opItems: (opId) => ['inventory', 'operations', opId, 'items'],
    },
  },
  superadmin: {
    dashboard: ['superadmin', 'dashboard'],
    companies: ['superadmin', 'companies'],
    users: ['superadmin', 'users'],
    plans: ['superadmin', 'plans'],
  },
};
